// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1yt-yt3yUWXl1qAhXRyUMNCCmBkVVJtw',
    appId: '1:575149452507:android:5cfc77bd47e7d906baf0fe',
    messagingSenderId: '575149452507',
    projectId: 'tistabenewholesale',
    storageBucket: 'tistabenewholesale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATMlKYzjF3ypsjwQjP5IFY5AZJaD0LVO8',
    appId: '1:575149452507:ios:372e9c11bf065fe6baf0fe',
    messagingSenderId: '575149452507',
    projectId: 'tistabenewholesale',
    storageBucket: 'tistabenewholesale.firebasestorage.app',
    iosBundleId: 'com.tistabene.wholesaler',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8KUuFuRHj5QOJO5AHT_VLpdljcjYYmo',
    appId: '1:142323472:web:ec567e65c7a1c097a23f95',
    messagingSenderId: '142323472',
    projectId: 'tistabene-f58a4',
    authDomain: 'tistabene-f58a4.firebaseapp.com',
    storageBucket: 'tistabene-f58a4.firebasestorage.app',
    measurementId: 'G-BBJRLYV61K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqUR69MFzfdfOg5eTfGIWo8FZvIheEp8',
    appId: '1:142323472:ios:a83aeeecd9758a65a23f95',
    messagingSenderId: '142323472',
    projectId: 'tistabene-f58a4',
    storageBucket: 'tistabene-f58a4.firebasestorage.app',
    iosBundleId: 'com.inilabs.shopking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW8KUuFuRHj5QOJO5AHT_VLpdljcjYYmo',
    appId: '1:142323472:web:a77837f01d3ba0e5a23f95',
    messagingSenderId: '142323472',
    projectId: 'tistabene-f58a4',
    authDomain: 'tistabene-f58a4.firebaseapp.com',
    storageBucket: 'tistabene-f58a4.firebasestorage.app',
    measurementId: 'G-E88P321WV4',
  );

}